collabit/config/routes.rb
Collabit::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "log_in"
  get "create_user" => "users#new", :as => "create_user"
  get "home" => "home#index", :as => "home"
  get "latest" => "status#latest_updates",:as => "latest"
  post "statuses" => "status#view_before_save", :as => "statuses"
  post "save_status" => "status#save_status", :as => "save_status"
  post "view_status" => "status#view_status", :as => "view_status"
  get "view_statuses" => "status#view_statuses", :as => "view_statuses"
  post "edit_status" => "status#edit_status", :as => "edit_status"
  post "view_before_save" => "status#view_before_save", :as => "view_before_save"
  get "create" => "status#create", :as => "create"
  get "view_profile" => "profile#view", :as => "view_profile"
  get "edit_profile" => "profile#edit", :as => "edit_profile"
  post "save_profile" => "profile#save", :as => "save_profile"
  get  "admin" => "admin#index", :as => "admin"
  get  "edit_users" => "users#edit", :as => "edit_users"
  get "modify_user" => "users#modify", :as => "modify_user"
  post "save_user" => "users#save", :as => "save_user"
  post "delete_user" => "users#delete", :as => "delete_user"
  get  "awaiting_review" => "status#awaiting_review", :as => "awaiting_review"
  
  resources :users
  resources :sessions

  root :to => 'sessions#new'
end

collabit/app/models/status.rb
class Status < ActiveRecord::Base

  
end

collabit/app/controllers/status_controller.rb
class StatusController < ApplicationController
  before_filter :authenticated
  helper_method :statuses, :last_edited_by_email
  
  def create
    @status = Status.new
    render :layout => "create"
  end
  
  def view_before_save
    if not params_blank?(params)      
      @details = {:we => params[:week_ending], :title => params[:title], :status => params[:status]}   
    else
      flash[:error] = "Sorry Charlie, your report is missing something"
      redirect_to create_path
    end
  end
  
  def save_status
    if !params_blank?(params)
       status = params[:id].present? ? Status.find_by_id(params[:id]) : Status.new
      if status && status.id
       status.update_attributes(:id => status.id, :title => params[:title], :week_ending => params[:week_ending], :status => params[:status], :team_number => current_user_team_id, :last_edited_by => current_user.user_id)
      elsif status
        status.title = params[:title]
        status.week_ending  = params[:week_ending]
        status.status = params[:status]
        status.team_number = current_user.role
        status.last_edited_by = current_user.user_id
        status.save!
      end 
    else
      redirect_to home_url
      flash[:notice] = "Your changes were not saved, something went wrong!"
    end
  end
  
  def latest_updates
    str = ''
    status = Status.all
    nstatus = status.last(3).sort_by{ |update| update.updated_at}.reverse
    
    nstatus.each do |update|
    str << "<div class=\"span8\">"
    str << "<h2>\"#{h(update.title[0..30])}\"</h2>"
    str << "<p>was updated by: #{h(editor(update.last_edited_by))}</p>"  
    str << "</div>"
    end 
    
    render :text => str
      
  end
  
  def editor(num=0)
    writer = User.find_by_user_id(num)
    return writer.email
  end
  
  def statuses
    all_stats = {}
    week_ending_statuses = Status.find(:all, :select => "week_ending").map(&:week_ending).uniq!
    week_ending_statuses.each {|s| all_stats[s] = []}
    all_statuses = Status.all.sort_by {|status| status.week_ending}
    all_statuses.each do |status|
      all_stats[status.week_ending].push(status) if all_stats.has_key?(status.week_ending)
    end
    return all_stats
  end
  
  def status_for_team(all_stats, team_num)
    return [] unless all_stats.present? and team_num.present?
    return [] unless all_stats.kind_of?(Array) && team_num.kind_of?(Integer)
    statuses = all_stats.map {|s|  s if (s.team_number == team_num)}.delete_if {|x| x.nil?}
    return statuses
  end
  
  def single_status(id)
   return Status.find_by_id(id) if id
  end
  
  def view_status  
    redirect = false
    if !params_blank?(params)
      stats = params.map {|x,y| {x => y} if x.to_s.match(/status_report_+(\d*)\z/)}
      @status_reports = choose_statuses_by_id(stats.compact!)
      if @status_reports.empty?
        redirect = true
      end
    else
      redirect = true
    end
    redirect_to view_statuses_path if redirect 
  end
  
  def view_statuses
  end
  
  def awaiting_review
    @status_for_review = pending_review_statuses
    redirect_to view_statuses if @status_for_review.nil?
  end 
  
  def edit_status
    @single_s = single_status(params[:id]) if params[:id]
    if @single_s.present? && (current_user_team_id == @single_s.team_number || current_user_role == "admin")
      render :layout => "edit_status"
    else
      redirect_to view_statuses_path
      flash[:error] = "You do not have permissions to edit this team's status"
    end 
  end
  
private

  def last_edited_by_email(email_id = '')
    return email_id if email_id.to_s.empty?
    u =  User.find_by_id(email_id)
    email_id = u.email if u.respond_to?('email')
    return email_id
  end 
  
end

collabit/app/helpers/status_helper.rb
module StatusHelper
end

collabit/app/views/status/awaiting_review.html.erb
<div align="center">

	<h1>Report(s) for review</h1>

<!-- This is where the table that contains status reports awaiting approval starts-->
    <%= form_tag view_status_path do  %>
		<table class="table table-striped" style="margin-top: 25px; width: 30%">
			<thead>
				<tr>
			      <th>Week Ending</th>
			    </tr>
			  </thead>
			  <tbody>
				<% pending_review_statuses.each do |status_report| %>
			    <tr>
					<td>
						<label>
							<%= check_box_tag "status_report_#{status_report.id}", "#{status_report.id}", false, :class => "checkbox" %>
							<b> <%= "#{status_report.week_ending}" %> </b>
						</label>
						
					</td>
			    </tr>
				<% end %>
			</tbody>
		</table>
		<%= submit_tag "Submit", {:method => "post", :class => "btn btn-primary"}%>		
<% end %>
<!-- end of table-->
</div>

collabit/app/views/status/create.html.erb
<div align="center">
<% flash.each do |name, msg| %>
	<% if name == :error %> 
		<div class="alert alert-error" style="width: 20%; margin-top: 50px">
			<a class="close" data-dismiss="alert" href="#">×</a>
  				<%= content_tag :div, msg, :id => "flash_notice" %>
		</div>
	<% elsif name == :success %>
		<div class="alert alert-success" style="width: 20%; margin-top: 50px">
			<a class="close" data-dismiss="alert" href="#">×</a>
  				<%= content_tag :div, msg, :id => "flash_notice" %>
		</div>
	<% elsif name == :info %>
		<div class="alert alert-info" style="width: 20%; margin-top: 50px">
			<a class="close" data-dismiss="alert" href="#">×</a>
				<%= content_tag :div, msg, :id => "flash_notice" %>
		</div>
	<% end %>
</div>	
		
<% end %>
 <div class="editor" align="center" >
 	<%= form_tag(view_before_save_path,  {:method => "post"}) %>
	 <p>
	  <%= label_tag(:title, "Title") %><br/>
	  <%= text_field_tag :title, nil, {:class => "input-large"}%><br/>
	 </p>
	 <p>
	  <%= label_tag(:week_ending, "Week Ending") %><br/>
	  <%= calendar_date_select_tag :week_ending, nil, {:class => "input-large", :embed => true, :size => 28} %><br/>
	 </p>
	 <%= text_area_tag :status, nil, {:style => "width:1000px;height:300px"} %>
	 <%= raw(puny_mce 'status', 'status', :profile => :all) %>
	 <p>
	  <%= submit_tag 'save', {:class => "btn btn-primary", :style => "margin-top: 20px"} %>
	 </p>
 </div>

collabit/app/views/status/edit_status.html.erb
<div align="center">
	<h1>Edit a status report</h1>
	<% flash.each do |name, msg| %>
		<% if name == :error %> 
			<div class="alert alert-error" style="width: 20%; margin-top: 50px">
				<a class="close" data-dismiss="alert" href="#">×</a>
	  				<%= content_tag :div, msg, :id => "flash_notice" %>
			</div>
		<% elsif name == :success %>
			<div class="alert alert-success" style="width: 20%; margin-top: 50px">
				<a class="close" data-dismiss="alert" href="#">×</a>
	  				<%= content_tag :div, msg, :id => "flash_notice" %>
			</div>
		<% elsif name == :info %>
			<div class="alert alert-info" style="width: 20%; margin-top: 50px">
				<a class="close" data-dismiss="alert" href="#">×</a>
					<%= content_tag :div, msg, :id => "flash_notice" %>
			</div>
		<% end %>
</div>

<% end %>
 <div class="editor" align="center" >
  <%= form_tag(save_status_path(:id => @single_s.id), {:method => "post"}) %>
 <p>
  <%= label_tag(:title, "Title") %><br/>
  <%= text_field_tag(:title,  @single_s.title)%><br/>
 </p>
 <p>
  <%= label_tag(:week_ending, "Week Ending") %><br/>
  <%= calendar_date_select_tag :week_ending, @single_s.week_ending, :embed => true, :size => 28%><br/>
 </p>
 <%= text_area_tag(:status,  @single_s[:status], {:style => "width:1000px;height:300px"}) %>
 <%= raw(puny_mce 'status', 'status', :profile => :all) %>
 <p>
  <%= submit_tag 'save', {:class => "button_home"} %>
 </p>
 </div>

collabit/app/views/status/save_status.html.erb
<h1> Successfully Saved! </h1>

<div id="back" align="center">
  <%= button_to "Back", home_path, {:method => "get", :class => "button_home"} %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_notice" %>
<% end %>

collabit/app/views/status/view_before_save.html.erb
<h1> Review </h1>

<table class= "table" align="center" border="0" cellpadding="5" cellspacing="5">
  <tr>
  <th>Title</th>
  <th><%= @details[:title]%></th>
  </tr>
  <tr>
  <th>Week Ending</th>
  <th><%= @details[:we]%></th>
  </tr>
  </tr>
  <tr>
  <th>Status</th>
  <th><%= raw(@details[:status])%></th>
  </tr>
</table>

<div id="confirm_or_deny" align="center" >
  

  <%= button_to("Confirm", {:action => "save_status", :week_ending => @details[:we], :status => @details[:status], :title => @details[:title]}, {:class => "btn btn-large btn-primary"}) %>
  <%= button_to "Deny", {:action => "create"}, {:method => "get", :class => "btn btn-large btn-danger"} %>
</div>

collabit/app/views/status/view_status.html.erb
<%= include_puny_mce %>

<div class="subnav">
  <ul class="nav nav-pills">
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">Current Reports<b class="caret"></b></a>
      <ul class="dropdown-menu">
			<% if pending_review_statuses.empty?%>
				<li><%= link_to "Awaiting Review <span class=\"badge\">0</span>".html_safe, "#" %><li>
			<% else%>
				<li><%= link_to "Awaiting Review <span class=\"badge badge-important\">#{pending_review_statuses.length}</span>".html_safe, awaiting_review_path %><li>
			<% end %>
		  <li><a href="#navs">Drafts</a></li>
      </ul>
    </li>
    <li><a href="#labels">Older Reports</a></li>
  </ul>
</div>

<div align="center">

	<h1> Combine Status Reports</h1>
	<% flash.each do |name, msg| %>
		<% if name == :error %> 
			<div class="alert alert-error" style="width: 20%; margin-top: 50px">
				<a class="close" data-dismiss="alert" href="#">×</a>
	  				<%= content_tag :div, msg, :id => "flash_notice" %>
			</div>
		<% elsif name == :success %>
			<div class="alert alert-success" style="width: 20%; margin-top: 50px">
				<a class="close" data-dismiss="alert" href="#">×</a>
	  				<%= content_tag :div, msg, :id => "flash_notice" %>
			</div>
		<% elsif name == :info %>
			<div class="alert alert-info" style="width: 20%; margin-top: 50px">
				<a class="close" data-dismiss="alert" href="#">×</a>
					<%= content_tag :div, msg, :id => "flash_notice" %>
			</div>
		<% end %>
	<% end %>
	
	<div class="accordion" id="accordion2" style="margin-top: 25px; width: 1000px; height:300px">
		<div class="accordion-group">
	    	<div class="accordion-heading">
	        	<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
	            	New Report
	            </a>
	        </div>
	        <div id="collapseOne" class="accordion-body collapse in">
	        	<div class="accordion-inner">
	            	<div class="editor" align="center" >
						<%= form_tag(view_before_save_path,  {:method => "post"}) %>
						<%= text_area_tag :status, nil, {:style => "width:1000px;height:300px"} %>
						<p>
							<%= raw(puny_mce 'status', 'status', :profile => :all) %>
							<%= submit_tag 'save', {:class => "btn btn-primary", :style => "margin-top: 20px"} %>
						</p>
					</div>
				</div>
	        </div>
		</div>
		<% @status_reports.each_with_index do |report, index| %>
		<div class="accordion-group">
	    	<div class="accordion-heading">
	        	<%= "<a class=\"accordion-toggle\" data-toggle=\"collapse\" data-parent=\"#accordion2\" href=\"#collapse#{index}\">".html_safe %>
	            	<%= "#{last_edited_by_email(report.last_edited_by)}".html_safe %>
	            </a>
	        </div>
	        <%= "<div id=\"collapse#{index}\" class=\"accordion-body collapse in\">".html_safe %>
	        	<div class="accordion-inner">
	            	<div class="editor" align="center" >
						<%= form_tag(view_before_save_path,  {:method => "post"}) %>
						<%= text_area_tag :status, report.status, {:style => "width:1000px;height:300px"} %>
					</div>
				</div>
	        </div>
		</div>
		<% end %>
	</div>

collabit/app/views/status/view_statuses.html.erb
  <div class="subnav">
    <ul class="nav nav-pills">
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Current Reports<b class="caret"></b></a>
        <ul class="dropdown-menu">
			<% if pending_review_statuses.empty?%>
				<li><%= link_to "Awaiting Review <span class=\"badge\">0</span>".html_safe, "#" %><li>
			<% else%>
				<li><%= link_to "Awaiting Review <span class=\"badge badge-important\">#{pending_review_statuses.length}</span>".html_safe, awaiting_review_path %><li>
			<% end %>
		  <li><a href="#navs">Drafts</a></li>
        </ul>
      </li>
      <li><a href="#labels">Older Reports</a></li>
    </ul>
  </div>

<div align="center">
	<h1> Status Reports </h1>
	<% flash.each do |name, msg| %>
		<% if name == :error %> 
			<div class="alert alert-error" style="width: 20%; margin-top: 50px">
				<a class="close" data-dismiss="alert" href="#">×</a>
	  				<%= content_tag :div, msg, :id => "flash_notice" %>
			</div>
		<% elsif name == :success %>
			<div class="alert alert-success" style="width: 20%; margin-top: 50px">
				<a class="close" data-dismiss="alert" href="#">×</a>
	  				<%= content_tag :div, msg, :id => "flash_notice" %>
			</div>
		<% elsif name == :info %>
			<div class="alert alert-info" style="width: 20%; margin-top: 50px">
				<a class="close" data-dismiss="alert" href="#">×</a>
					<%= content_tag :div, msg, :id => "flash_notice" %>
			</div>
		<% end %>
	<% end %>
</div>
	