koala_meat/config/routes.rb
KoalaMeat::Application.routes.draw do
  get "test" => "users#test", :as => "test"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "admin"   => "admin#portal", :as => "admin"
  get "forgot_password" => "users#forgot_password", :as => "forgot_password"
  post "forgot_password" => "users#forgot_password", :as => "forgot_password"
  get "catalog" => "home#catalog", :as => "catalog"
  get "contact_us" => "home#contact_us", :as => "contact_us"
  get "about_us" => "home#about_us", :as => "about_us"
  post "clean_up" => "admin#clean_up", :as => "clean_up"
  get "show_catalog_item", :to => "home#show_catalog_item", :as => "show_catalog_item"
  
  match '/maint', :to => "admin#maint", :as => "maint"
  match '/mgmt', :to => "admin#mgmt", :as => "mgmt"
  match '/mgmt/edit_user', :to => "admin#edit_user", :as => "edit_user"
  match '/users/update', :to => "users#update", :as => "update"
  resources :users
  resources :sessions
  
  root :to => 'home#index'
  
  # This catches 404's and just redirects back to home
  match "*path" => 'error#handle404'
 
end

koala_meat/app/views/admin/edit_user.html.erb
<div align="center">
<h1> Edit User </h1>

<div >
  <% if @user %>
  <%=form_for(@user) do |f|%>
    <p>
      <%= f.label :email %>
      <br>
      <%= f.text_field :email, {:class => "textbox"} %>
      </br>
    </p>
    <p>
      <%= f.label :password %>
      <br>
      <%= f.password_field :password, {:class => "textbox"} %>
      </br>
    </p>
    <p>
      <%= f.label :password_confirmation %>
      <br>
      <%= f.password_field :password_confirmation %>
      </br>
      <br>
        <p>
           <%= f.label :admin %>
           <br>
          <%= select("user", "admin", UsersController.role_bool, { :include_blank => false }) %>
           </br>
        </p>
      </br>
    </p>
      <%= button_to "Update", update_path, {:class => "btn btn-success"}%>
    <% end %>
    <% else %>
      <script> alert('CAN\'T FAULT YOU FOR TRYING!')</script>
  <% end %>
</div>
<div align="center">

koala_meat/app/views/admin/maint.html.erb
<div align="center">

<h1> Database Maintenance </h1>
<% flash.each do |name, msg| %>
		<% if name == :error %> 
			<div class="alert alert-error" style="width: 20%; margin-top: 50px">
				<a class="close" data-dismiss="alert" href="#">×</a>
	  				<%= content_tag :div, msg, :id => "flash_notice" %>
			</div>
		<% elsif name == :success %>
			<div class="alert alert-success" style="width: 20%; margin-top: 50px">
				<a class="close" data-dismiss="alert" href="#">×</a>
	  				<%= content_tag :div, msg, :id => "flash_notice" %>
			</div>
		<% elsif name == :info %>
			<div class="alert alert-info" style="width: 20%; margin-top: 50px">
				<a class="close" data-dismiss="alert" href="#">×</a>
					<%= content_tag :div, msg, :id => "flash_notice" %>
			</div>
		<% end %>


	<% end %>
 
<ul style="display: inline-block; margin-top: 25px" class="nav nav-tabs">
	<li><%= link_to "Administration", admin_path %></li>
	<li class="active"><%= link_to "DB Maint.", maint_path %></li>
	<li><%= link_to  "User Mgmt.", mgmt_path %></li>
</ul>

<%= form_tag(clean_up_path, :method => "post") do %>
  <%=  hidden_field "file", 'cleanup.rb' %>
  <%=  submit_tag "Cleanup Function", {:class => "btn btn-success"} %>
<% end %>

</div>

koala_meat/app/views/admin/mgmt.html.erb
<div align="center">

<h1> User Management </h1>

<% flash.each do |name, msg| %>
		<% if name == :error %> 
			<div class="alert alert-error" style="width: 20%; margin-top: 50px">
				<a class="close" data-dismiss="alert" href="#">×</a>
	  				<%= content_tag :div, msg, :id => "flash_notice" %>
			</div>
		<% elsif name == :success %>
			<div class="alert alert-success" style="width: 20%; margin-top: 50px">
				<a class="close" data-dismiss="alert" href="#">×</a>
	  				<%= content_tag :div, msg, :id => "flash_notice" %>
			</div>
		<% elsif name == :info %>
			<div class="alert alert-info" style="width: 20%; margin-top: 50px">
				<a class="close" data-dismiss="alert" href="#">×</a>
					<%= content_tag :div, msg, :id => "flash_notice" %>
			</div>
		<% end %>


	<% end %>


<ul style="display: inline-block; margin-top: 25px" class="nav nav-tabs">
	<li><%= link_to "Administration", admin_path %></li>
	<li><%= link_to "DB Maint.", maint_path %></li>
	<li class="active"><%= link_to  "User Mgmt.", mgmt_path %></li>
</ul>


<div class="container">
<table class="table table-bordered" align="center" style="margin-top: 25px">
  <tr>
  <th>Username</th>
  <th>Role: Admin</th>
  </tr>
  <% users.each do |email, role| %>   
  <tr>  
    <td width="20%"><%=link_to email, edit_user_path(:user_id => email)%></td><td><%=role%></td>
  </tr>
  <% end %>
  </table>
</div>
</div>

koala_meat/app/views/admin/portal.html.erb
<div align="center">
<h1> Admin Portal </h1>
    <% flash.each do |name, msg| %>
		<% if name == :error %> 
			<div class="alert alert-error" style="width: 20%; margin-top: 50px">
				<a class="close" data-dismiss="alert" href="#">×</a>
	  				<%= content_tag :div, msg, :id => "flash_notice" %>
			</div>
		<% elsif name == :success %>
			<div class="alert alert-success" style="width: 20%; margin-top: 50px">
				<a class="close" data-dismiss="alert" href="#">×</a>
	  				<%= content_tag :div, msg, :id => "flash_notice" %>
			</div>
		<% elsif name == :info %>
			<div class="alert alert-info" style="width: 20%; margin-top: 50px">
				<a class="close" data-dismiss="alert" href="#">×</a>
					<%= content_tag :div, msg, :id => "flash_notice" %>
			</div>
		<% end %>


	<% end %>

 <ul style="display: inline-block; margin-top: 25px" class="nav nav-tabs">
	<li class="active"><%= link_to "Administration", admin_path %></li>
 	<li><%= link_to "DB Maint.", maint_path %></li>
 	<li><%= link_to  "User Mgmt.", mgmt_path %></li>
 </ul>

</div>