collabit/config/routes.rb
Collabit::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "log_in"
  get "create_user" => "users#new", :as => "create_user"
  get "home" => "home#index", :as => "home"
  get "latest" => "status#latest_updates",:as => "latest"
  post "statuses" => "status#view_before_save", :as => "statuses"
  post "save_status" => "status#save_status", :as => "save_status"
  post "view_status" => "status#view_status", :as => "view_status"
  get "view_statuses" => "status#view_statuses", :as => "view_statuses"
  post "edit_status" => "status#edit_status", :as => "edit_status"
  post "view_before_save" => "status#view_before_save", :as => "view_before_save"
  get "create" => "status#create", :as => "create"
  get "view_profile" => "profile#view", :as => "view_profile"
  get "edit_profile" => "profile#edit", :as => "edit_profile"
  post "save_profile" => "profile#save", :as => "save_profile"
  get  "admin" => "admin#index", :as => "admin"
  get  "edit_users" => "users#edit", :as => "edit_users"
  get "modify_user" => "users#modify", :as => "modify_user"
  post "save_user" => "users#save", :as => "save_user"
  post "delete_user" => "users#delete", :as => "delete_user"
  get  "awaiting_review" => "status#awaiting_review", :as => "awaiting_review"
  
  resources :users
  resources :sessions

  root :to => 'sessions#new'
end

collabit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Collabit</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
	
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag("bootstrap_and_overrides")%>
  <%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">


 	<div class="navbar navbar-fixed-top">
		
      <div class="navbar-inner">
		<div class="container-fluid">
			<div class="navbar-search pull-right">
				<ul class="nav">
					<% if not current_user %>
						<li><%= link_to "Login", log_in_path  %></li>
					<% else%>
						
						<% if current_user_role == "admin"%>
							<!-- This is the administration link -->

								<li><%= link_to "Administration", admin_path, {:class => "active"}%></li>

							<!-- end -->
						<% end %>
					
					    <!-- This is the drop down to edit your profile -->
						<li class="dropdown">
			    			<a href="#" class="dropdown-toggle"	data-toggle="dropdown">
			            		Profile
			              		<b class="caret"></b>
			            	</a>
			            	<ul class="dropdown-menu">			            	
								<li><%= link_to "Edit", edit_profile_path  %></li>
			            	</ul>
						</li>
						 <!-- end -->
						<li><%= link_to "Logout", logout_path  %></li>
					<% end %>
				</ul>
			</div>
			<ul class="nav nav-pills">
		 		<a class="brand">Collabit</a>
		  		<% if current_user %>
				<li><%= link_to "Home", home_path, {:class => "active"}%></li>
		  			<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
			            	<% if pending_review_statuses.empty? %>
								Status Reports
							<% else %>
								<%= "Status Reports <span class=\"badge badge-important\">#{pending_review_statuses.length}</span>".html_safe %>
							<% end %>
			              	<b class="caret"></b>
			            </a>
			            <ul class="dropdown-menu">
			            	<li><%= link_to "Create", create_path %></li>
			                <li><%= link_to "View", view_statuses_path%></li>
			            </ul>
					</li>
				</li>
				<% end %>
			</ul>
		</div>
      </div>
    </div>
</head>
<body>
  <div class="container-fluid">
  		<%= yield %>
	</div>
</body>

</html>

collabit/app/views/layouts/create.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Collabit</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
	<%= javascript_include_tag("application")%>
	<%= stylesheet_link_tag("bootstrap_and_overrides")%>
	<%= javascript_include_tag("https://ajax.googleapis.com/ajax/libs/prototype/1.7.0.0/prototype.js") %>
	<%= include_puny_mce %>
	<%= calendar_date_select_includes :style => "plain"%>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">


 	<div class="navbar navbar-fixed-top">
		
      <div class="navbar-inner">
		<div class="container-fluid">
			<div class="navbar-search pull-right">
				<ul class="nav">
					<% if not current_user %>
						<li><%= link_to "Login", log_in_path  %></li>
					<% else%>
						<% if current_user_role == "admin"%>
						<!-- This is the administration link -->
						
							<li><%= link_to "Administration", admin_path, {:class => "active"}%></li>
						
						<!-- end -->
						<% end %>
					
					    <!-- This is the drop down to edit your profile -->
						<li class="dropdown">
			    			<a href="#" class="dropdown-toggle"	data-toggle="dropdown">
			            		Profile
			              		<b class="caret"></b>
			            	</a>
			            	<ul class="dropdown-menu">			            	
								<li><%= link_to "Edit", edit_profile_path  %></li>
			            	</ul>
						</li>
						 <!-- end -->
						<li><%= link_to "Logout", logout_path  %></li>
					<% end %>
				</ul>
			</div>
			<ul class="nav nav-pills">
		 		<a class="brand">Collabit</a>
		  		<% if current_user %>
				<li><%= link_to "Home", home_path, {:class => "active"}%></li>
		  			<li class="dropdown">
			    		<a href="#" class="dropdown-toggle"	data-toggle="dropdown">
			            	<% if pending_review_statuses.empty? %>
								Status Reports
							<% else %>
								<%= "Status Reports <span class=\"badge badge-important\">#{pending_review_statuses.length}</span>".html_safe %>
							<% end %>
			              	<b class="caret"></b>
			            </a>
			            <ul class="dropdown-menu">
			            	<li><%= link_to "Create", create_path %></li>
			                <li><%= link_to "View", view_statuses_path%></li>
			            </ul>
					</li>
				</li>
				<% end %>
			</ul>
		</div>
      </div>
    </div>
</head>
<body>
  <div class="container">
  		<%= yield %>
	</div>
</body>

</html>

collabit/app/views/layouts/edit_status.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Collabit</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
	<%= javascript_include_tag("application")%>
	<%= stylesheet_link_tag("bootstrap_and_overrides")%>
	<%= javascript_include_tag("https://ajax.googleapis.com/ajax/libs/prototype/1.7.0.0/prototype.js") %>
	<%= include_puny_mce %>
	<%= calendar_date_select_includes :style => "plain"%>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">


 	<div class="navbar navbar-fixed-top">
		
      <div class="navbar-inner">
		<div class="container-fluid">
			<div class="navbar-search pull-right">
				<ul class="nav">
					<% if not current_user %>
						<li><%= link_to "Login", log_in_path  %></li>
					<% else%>
						<% if current_user_role == "admin"%>
						<!-- This is the administration link -->
						
							<li><%= link_to "Administration", admin_path, {:class => "active"}%></li>
						
						<!-- end -->
						<% end %>
					
					    <!-- This is the drop down to edit your profile -->
						<li class="dropdown">
			    			<a href="#" class="dropdown-toggle"	data-toggle="dropdown">
			            		Profile
			              		<b class="caret"></b>
			            	</a>
			            	<ul class="dropdown-menu">			            	
								<li><%= link_to "Edit", edit_profile_path  %></li>
			            	</ul>
						</li>
						 <!-- end -->
						<li><%= link_to "Logout", logout_path  %></li>
					<% end %>
				</ul>
			</div>
			<ul class="nav nav-pills">
		 		<a class="brand">Collabit</a>
		  		<% if current_user %>
				<li><%= link_to "Home", home_path, {:class => "active"}%></li>
		  			<li class="dropdown">
			    		<a href="#" class="dropdown-toggle"	data-toggle="dropdown">
			            	<% if pending_review_statuses.empty? %>
								Status Reports
							<% else %>
								<%= "Status Reports <span class=\"badge badge-important\">#{pending_review_statuses.length}</span>".html_safe %>
							<% end %>
			              	<b class="caret"></b>
			            </a>
			            <ul class="dropdown-menu">
			            	<li><%= link_to "Create", create_path %></li>
			                <li><%= link_to "View", view_statuses_path%></li>
			            </ul>
					</li>
				</li>
				<% end %>
			</ul>
		</div>
      </div>
    </div>
</head>
<body>
  <div class="container">
  		<%= yield %>
	</div>
</body>

</html>