koala_meat/config/routes.rb
KoalaMeat::Application.routes.draw do
  get "test" => "users#test", :as => "test"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "admin"   => "admin#portal", :as => "admin"
  get "forgot_password" => "users#forgot_password", :as => "forgot_password"
  post "forgot_password" => "users#forgot_password", :as => "forgot_password"
  get "catalog" => "home#catalog", :as => "catalog"
  get "contact_us" => "home#contact_us", :as => "contact_us"
  get "about_us" => "home#about_us", :as => "about_us"
  post "clean_up" => "admin#clean_up", :as => "clean_up"
  get "show_catalog_item", :to => "home#show_catalog_item", :as => "show_catalog_item"
  
  match '/maint', :to => "admin#maint", :as => "maint"
  match '/mgmt', :to => "admin#mgmt", :as => "mgmt"
  match '/mgmt/edit_user', :to => "admin#edit_user", :as => "edit_user"
  match '/users/update', :to => "users#update", :as => "update"
  resources :users
  resources :sessions
  
  root :to => 'home#index'
  
  # This catches 404's and just redirects back to home
  match "*path" => 'error#handle404'
 
end

koala_meat/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Koala Meat</title>
  <!--[if lt IE 9]>
    
  <![endif]-->

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag("bootstrap_and_overrides")%>
  <%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">


 	<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
		<div class="container-fluid">
			<div class="navbar-search pull-right">
				<ul class="nav">
					<% if not current_user %>
						<li><%= link_to "Login", log_in_path, {:style => "color: #FFFFFF"} %></li>
						<li><%= link_to "Signup", sign_up_path, {:style => "color: #FFFFFF"} %></li>
					<% else %>
						 <!-- begin admin code -->
						   <% if is_admin? %>
						   <li><%= link_to "Administration", admin_path, {:style => "color: #FFFFFF"}   %></li>
						   <% end %>
						 <!-- end -->
						<li><%= link_to "Logout", log_out_path, {:style => "color: #FFFFFF"}   %></li>
					<% end %>
				</ul>
			</div>
			<ul class="nav nav-pills">
		 		<a class="brand" style="color: #FFFFFF">Koala Meat</a>
					<li><%= link_to "Home", root_path, {:class => "active", :style => "color: #FFFFFF"}%></li>
			</ul>
		</div>
      </div>
    </div>
</head>
<body>
  <div class="container-fluid">
  		<%= yield %>
	</div>
</body>

</html>